### ISSUE TITLE
undo error 

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#1]
Occasionally, whe I try to UNDO the text (both using ctrl+Z and from the edit menu) the command does not work and undoing an edit is impossible. 
That happens either after having saved the text and without saving the text.

Tested on: Debian Buster, Devuan Beowulf, Devuan Chimaera.

**Comment by limburgher** [comment]
Do you have an example of text that consistently causes this? Any particular section type, character content, etc?

**Comment by maccagnan** [comment]
b'Do you have an example of text that consistently'
b'causes this'
b'Any particular section '
b', character content, etc?'

At times an N appears instead of a B at the beginning of the text.

**Comment by limburgher** [comment]
For the undo issue? This looks like the system copy/paste issue.

**Comment by maccagnan** [comment]
You're right, confused the thread, sorry! :(

**Comment by maccagnan** [comment]
The undo error seems related to the prompt getting stuck at times, when you have to open a new file in order un unblock it. I haven't noticed a particular word bringing about the undo error, but it happens frequently enough.
It seem more frequent when the undo is spread through different element such as description, dialogue, etc.

**Comment by limburgher** [comment]
Interesting, I've never encountered that. Is the desktop environment you're using with this all XFCE?

**Comment by maccagnan** [comment]
I use Jwm an all my systems, so I don't know if that might be the cause. It never happened on 2.3 though.  
Just tested again, and it's definitely more prone when the undo is spread through different element such as description, dialogue, etc.

**Comment by limburgher** [comment]
Ah, I've reproduced it. Now to work out how to fix it. :)

**Comment by maccagnan** [comment]
Great. So far I haven't encountered other Issues.
