### ISSUE TITLE
Useful keyboard shortcuts.

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#12]
This is to allow users to suggest keyboard shortcuts which might be useful.
My top request would be shortcuts to copy and to paste from system, which is now possible only from the Edit menu.
Also a shotcut to launch the spell checker would be nice. 
By the way, CTRL+A works to select all text but does not appear beside the 'select all' tab in the Edit menu.

**Comment by allaboutmikey** [comment]
@maccagnan This is already possible.

Go into menu: File, Settings, Change
Choose Keyboard from the list on the left.
Choose the commands you want, then assign keys to them.

The commands you probably want are:
CopySystemCb, CopySystemCbFormatted, PasteSystemCb

BTW Thanks @limburgher for doing this. I was halfway through it myself before I stumbled on your effort.

**Comment by maccagnan** [comment]
@allaboutmikey Thanks a lot for your suggestion. I hadn't found this macro option yet.

**Comment by limburgher** [comment]
I'll consider this resolved, then. @allaboutmikey you're very welcome! If you still want to work on it, #9 and #11 could use some love. I've been looking at #9 but it's vexing, and I don't have the experience to do #11.
