### ISSUE TITLE
import .txt file failure

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#13]
Import a .txt file results in a blank, empty file. I also don't get the pop up window asking whether I want to import the text as action, dialogue, etc. I haven't tried other formats such as fountain, etc.

**Comment by limburgher** [comment]
Please see if this branch fixes this issue: https://github.com/limburgher/trelby/tree/text

**Comment by maccagnan** [comment]
Worked just fine. Thanks!

**Comment by limburgher** [comment]
Excellent!
