### ISSUE TITLE
Error Making Deb Pack

### ISSUE THREAD

**Issue by RJPalmer** [limburgher/trelby#16]
Scenario: running 'make deb' on Ubuntu 20.04. Getting the following error:

<pre>make -C doc html &amp;&amp; mv doc/manual.html .
make[1]: Entering directory &apos;/home/robertpalmer/Documents/GitHub/trelby/doc&apos;
xsltproc  \
           --output manual.html html-stylesheet.xsl manual.xml
warning: failed to load external entity &quot;/usr/share/sgml/docbook/xsl-stylesheets/xhtml/docbook.xsl&quot;
compilation error: file html-stylesheet.xsl line 3 element import
xsl:import : unable to load /usr/share/sgml/docbook/xsl-stylesheets/xhtml/docbook.xsl
make[1]: *** [Makefile:37: manual.html] Error 5
make[1]: Leaving directory &apos;/home/robertpalmer/Documents/GitHub/trelby/doc&apos;
make: *** [Makefile:18: manual.html] Error 2
</pre>

**Comment by RJPalmer** [comment]
Was able to resolve this issue by adding the following packages based on https://packages.ubuntu.com/focal/docbook-xml

- sgml-base
- sgml-data
- docbook-xml
- docbook-xsl

**Comment by limburgher** [comment]
Thanks, fixed in master.
