### ISSUE TITLE
Fountain Title page does not populate title page information

### ISSUE THREAD

**Issue by mwchase** [limburgher/trelby#18]
It looks like my options when it comes to a fountain document's title page fields are "insert as action lines" (so they end up after the generic title page), or uncheck that box (so they're discarded).

I'd like to have an option to put those fields into the title page in some way.

At a high level, this ties into my other issue, where I'd like it to be possible to invoke Trelby as some kind of command-line utility that doesn't expect the data to be changed between import and export.

**Comment by limburgher** [comment]
Can you post a super-simple, Hello World Fountain file that illustrates this?

**Comment by mwchase** [comment]
Let's see what GitHub lets me upload...
```fountain
Title: EXAMPLE FOUNTAIN FILE
Credit: by
Author: mwchase

FADE IN:
```
When I import that file, I get this dialogue box:
![Screenshot_20220320_213524](https://user-images.githubusercontent.com/882845/159195828-37170f96-02c9-4df4-b493-8c7b5b737b57.png)
![Screenshot_20220320_213754](https://user-images.githubusercontent.com/882845/159195827-8d5092f1-03c1-4d0b-9222-2316dd6630a4.png)
And the two outcomes from the generated PDF are:
[titles-as-action-lines.pdf](https://github.com/limburgher/trelby/files/8312636/titles-as-action-lines.pdf)
[titles-not-as-action-lines.pdf](https://github.com/limburgher/trelby/files/8312635/titles-not-as-action-lines.pdf)
Looking at the differences, we can see that it does detect the title lines *as title lines*, but neither option for handling them populates the values into here:
![Screenshot_20220320_213939](https://user-images.githubusercontent.com/882845/159195927-17fa54a2-3bab-442b-b71d-2fed9b1de6f4.png)

**Comment by limburgher** [comment]
Is that the literal .fountain file format?

**Comment by mwchase** [comment]
Yes.

**Comment by limburgher** [comment]
Ahh, gotcha. That's good info, thank you.

**Comment by juliaclement** [comment]
I've partially fixed this in my fork of trelby (no installers, etc available so please don't try to install it) in commit # d7c8a82033ee962ad63939598b31ed31b2e40151 .

There's a mismatch between Trelby's title pages and fountain which has led to a few too many heuristics for my comfort but if you want to grab it as the basis for a well engineered fix ...

At present the export turns the three default line blocks into Title: Author: and Contact: with other blocks in the form Keyword: Value into arbitrary lines. Import reverses this process, any lines that are not keyword: value are turned into notes at the start of the script -- the "Bad header line should go into script" line began as one of these.

Example export, which re-imports correctly:
Title:
    _**THE GRIN REAPER:**_
    _**THE BUNNY'S TALE**_
Author:
    Julia Clement
    additional dialogue
    Tessa Clement
    Ashes Phoenix
Contact:
    027-555-5555
    julia@example.com
Credit: Written by
Draft date: 21-07-2022
User Header: This is a random line

Bad header line should go into script

EXT. A GARDEN - DAY

BIRDY, an English blackbird, is hunting for worms. BIRDY pauses, looks up, ponders for a second, nods and flies off

EXT. A MIC STAND IN A CEMETERY - NIGHT.

**Comment by limburgher** [comment]
Excellent! I'd love to have pull requests from your fork, or RJPalmer's. Any work to fix any bug or build issue is welcome, and I'd ideally love to see it all merged upstream.

**Comment by juliaclement** [comment]
I can't work out how to generate a pull request from my fork to yours. I think I made a tactical error forking from RJPalmer's fork rather than yours. I might just go back to the start & reapply my patches to a fresh fork.

**Comment by limburgher** [comment]
Or I could add you as a collaborator to mine and you could do it in a branch.

**Comment by juliaclement** [comment]
Thank you, but I'm not planning on doing many changes to trelby. My intentions here are to be an end-user rather than a developer. I had two issues that were really bugging me:

1. ctrl+right, ctrl+left caused the screenplay window to stop accepting keyboard input. I made a very idiosyncratic fix for that
2. The inability to export those utf8 characters not in ISO-8859-1. I've since read trelby/trelby issue#8 and decided that replacing the pdf generator was more work than I wanted to undertake.

Exporting title page info to fountain was just a minor irritation, importing for symmetry

Longer term it's probably best that I have my own repo & send pull requests for anything that's not too tightly coupled with my rather idiosyncratic view of the world.

**Comment by limburgher** [comment]
That works for me.

**Comment by juliaclement** [comment]
I've recreated my fork but now forked from yours rather than RJPalmer's. When I tried to create a pull request it contains both of my commits so I created a new branch with just the fountain change cherry picked & did a pull request on that. I hope this works.

**Comment by limburgher** [comment]
Fantastic, it does. Thank you so much Julia!
