### ISSUE TITLE
Exit with unsaved change dialogue is counter intuitive

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#32]
Opposed to most other applications, the dialogue that appears when you want to exit the application with unsaved changes doesn't ask whether to save, but asks whether to exit without saving. If you don't read the question properly, you might assume the opposite question and click the opposing "yes" or "no" button (you might for example think "No, I don't want to save" and click "No").

![grafik](https://user-images.githubusercontent.com/8160319/188312043-fa257a9b-199c-40fc-9671-6f0d0de0026a.png)

At best, I think, buttons should contain a more concrete wording than "yes" or "no", but rather "Discard" and "Cancel" (or something similar).

Bonus points for adding a third option "Save".

**Comment by Cerabbite** [comment]
I updated the modal and I think that this is what you meant.
![image](https://user-images.githubusercontent.com/98265679/208302810-c15780a6-c3fe-4f1d-b6c8-048dcf0efa31.png)

**Comment by janopae** [comment]
This is exactly what I meant! Could you prepare a PR for that, @Cerabbite?

**Comment by Cerabbite** [comment]
I created a pull request #46 for it

**Comment by Cerabbite** [comment]
I believe this issue can be closed as #46 is closed
