### ISSUE TITLE
.deb in release

### ISSUE THREAD

**Issue by ppbrown** [limburgher/trelby#33]
To make it more straightforward for people to install, would you please add a .deb to your releases?

There's probably some nice automated way to do it.  But, the by hand method, is
(first make the .deb of course, then)
click on the release, edit it, and then drag-n-drop the deb into the target area.
Fairly easy.

**Comment by limburgher** [comment]
There is, and I've not set it up yet. I'll add them manually for now.

**Comment by limburgher** [comment]
Added for 2.4.6
