### ISSUE TITLE
Python Error after using INSTALL instructions

### ISSUE THREAD

**Issue by Yaanu** [limburgher/trelby#35]
I'm trying to use the instructions in INSTALL to put Trelby in my /usr/ folder, since my window manager shortcut settings won't seem to let me start a program from the usual "./bin/trelby" or any other file paths. However, while everything does install correctly, it won't actually load. Instead, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/trelby", line 4, in <module>
    __import__('pkg_resources').run_script('Trelby==2.4.6', 'trelby')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Trelby==2.4.6' distribution was not found and is required by the application
```

I did some Googling but couldn't find anything that seemed like it would work, and I never paid attention to all those free Python lessons I never took, so I'm gonna go ahead and ask here just in case someone else is smarter than me.
For the record, I'm using Arch Linux 5.19.13. I dunno if that matters but I figured it's worth sharing.

**Comment by limburgher** [comment]
Interesting. So specifically what steps did you run, after git clone?

**Comment by Yaanu** [comment]
I ran the initial instructions to install from source:

`git clone https://github.com/limburgher/trelby.git`
`cd trelby`
`pip3 install requirements.txt`
`./bin/trelby`

Then I ran the instruction from INSTALL to install it to /usr/local:

`sudo python3 setup.py install --prefix=/usr/local --install-lib=/usr/local/share/trelby --install-data=/usr/local/share`

I assumed those were older instructions meant for the original release of Trelby, but I wanted to give it a shot anyways to see if it would work. It almost did, but if I run `trelby` from a command prompt, the error I posted above is all I get back.

**Comment by limburgher** [comment]
Yeah, I think those instructions need updating. My primary focus has been porting to Python3, but I've been working on the packaging pieces bit by bit. I'll see if I can get this working.

What do you get when you run ./bin/trelby?

**Comment by Yaanu** [comment]
Running `./bin/trelby` when in the original `trelby` folder opens Trelby as expected, and no errors appear at all.
Well, besides `Debug: Adding duplicate image handler for 'PNG file'`.

**Comment by limburgher** [comment]
Ok, good, so it's a packaging issue, not a code issue. And I've seen that debug message before, I've been meaning to track it down.
