### ISSUE TITLE
Issue with the pull request checker for py311

### ISSUE THREAD

**Issue by Cerabbite** [limburgher/trelby#47]
I just created a pull request and it failed at py311 with this error ```ERROR:   py311: could not install deps [-rrequirements.txt]; v = InvocationError('/github/workspace/.tox/py311/bin/python -m pip install -rrequirements.txt', 1)```
I think it should use the ```-r requirements.txt``` instead of ```-rrequirements.txt```

**Comment by janopae** [comment]
I think this has been fixed with #67
