### ISSUE TITLE
Support non-Latin1 characters

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#61]
Original issue https://web.archive.org/web/20201226153814/https://github.com/oskusalerma/trelby/issues/85

**Comment by janopae** [comment]
Reasoning on how to resolve this issue from https://github.com/limburgher/trelby/issues/21#issuecomment-1290857326:

>Reading the discussion, it seems that Trelby used to at least support the [Latin 1 charset](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), which at least Ö, é and è should be part of.
>
>However, in the discussion it gets obvious that embedding special characters to PDFs seems to be complicated. In the discussion, someone raises the idea of not creating the PDF "by hand" in Trelby, but rather use a library for this, that handles all the nitty-gritty details (like special character treatment). To that, then-maintainer oskusalerma replies that these libraries also couldn't solve the issue (as generating PDFs with abritary Unicode characters and abritary fonts was an unsolvable issue), to which another user replies that this is BS.
>
>I agree that this is BS, as I have a little bit of experience with Apache FOP, which works using arbitrary unicode characters with abritary fonts.
>
>I think we should look into replacing the hand generating of PDFs with a library.
>
> There is an integration for Apache FOP into Python: https://pypi.org/project/pypfop/
> 
> But it bundles Java (because Apache FOP is written in Java), and this might be a bit huge for a dependency. Also, I'm not sure if Apache FOP supports any other API than FO, which is their declatative XML format for writing PDFs. This XML format is great for creating PDFs with a fixed layout and changing contents, but as there is a lot the user can configure about the layout in Trelby, I'm not sure if this would get in our way at some points. Also, this would be very different from the way our current PML works, which has an imperative API, directly accessible from Python (with no XML in between).
> 
> The Reportlab Toolkit is another very popular solution for creating PDFs in Python: https://pypi.org/project/reportlab/
> 
> It is written directly in Python, which should be much more lightweight than bundling Java. And it's made by a company that has specialised in PDF generation: https://www.reportlab.com/
> 
> The module itself uses a Python API, which is much closer to what we do with PML than using a declarative XML. But in case we need it, they also provide an additional module that parses declarative XML files and generates PDFs from them.
> 
> If we manage to port our PDF rendering code to a library like this, we're going to get rid of a lot of poorly documented and hardly tested source code. Bugs within that source code (like special characters not being supported) would vanish. I think we should give it a try.

**Comment by Cerabbite** [comment]
I have never worked with Apache FOP, but I have worked with Reportlab and I personally found it a great library. So my preference would be to use Reportlab

**Comment by UnisTorvalds** [comment]
Random user here.  Thanks for bringing up this issue.  Would love to see it resolved.

**Comment by janopae** [comment]
> Random user here. Thanks for bringing up this issue. Would love to see it resolved.

Lucky you! We just merged #59, which fixes this problem.

I think there is no release yet, but if you use the source code version from the `main` branch, you should be able to use non-Latin1 characters now.

**Comment by limburgher** [comment]
2.4.9 will be out shortly. :)

**Comment by UnisTorvalds** [comment]
I saw that!  It is indeed my lucky day :)
Thank you all for continuing to maintain this project!!!
