### ISSUE TITLE
TypeErrors on Python 3.8

### ISSUE THREAD

**Issue by jonafato** [limburgher/trelby#63]
Recent additions of static type annotations result in type errors under Python 3.8 as seen in [this actions run](https://github.com/limburgher/trelby/actions/runs/4418135539/jobs/7744837693). This is due to the use of builtin types as generics, which were introduced in 3.9 via [PEP 585](https://peps.python.org/pep-0585/). The simplest fix for this is likely to drop 3.8 support, but 3.8 can be supported via the `typing` module if 3.8 support is required. Happy to open a PR with the changes for either of these options.

**Comment by limburgher** [comment]
I'd prefer to support all supported Python 3 versions.
