### ISSUE TITLE
Odd dictionary behavior

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#8]
Today I ran the spellchecker on the newly edited script. 
The spellchecker marked the word <Sanders'> ( which replaced <Sanders's> through the script and was the origin of the previous search & replace issue). 
So far, nothing strange, since the spellchecker always marks words ending with '.
However, once I added <Sanders'> to the script dictionary, the spellchecker kept asking about every instance of the same word, over and over.
This has never happened before. 
I don't know if the cause of such behavior is some wrong enconding caused by the previous search & replace of the word <Sanders'> or a bona fide bug.
Just for curiosity, I replaced all <Sanders'> with <xxxx> and then replaced <xxxx> with Sanders'> again.
Then I ran the spellchecker one more time. Same thing, it kept marking each issue of <Sanders'> even after I added each one to the dictionary.
UPDATE
Even selecting Skip does not work.
UPDATE
Same problem with the word <Bruderschaft>
UPDATE
I think it is the 'add to dictionary' function that does not work properly, cause I ran spellchecker again and it keep marking words I already added in the previous pass.

**Comment by limburgher** [comment]
I think I've got this fixed, please test the issue-8 branch.

**Comment by maccagnan** [comment]
Will do.
Filed another issue about fonts.
By the way, git works on my working distro, so it was probably my setting on the other system.
PS I thought my FB nickname was rather original.


On Wed, 03 Mar 2021 07:12:32 -0800
Gwyn Ciesla <notifications@github.com> wrote:

> I think I've got this fixed, please test the issue-8 branch.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/limburgher/trelby/issues/8#issuecomment-789785497


-- 
amc252 <amc252@@gmail.com>

**Comment by maccagnan** [comment]
Dictionary in Branch-issue-8 seems to work fine. :)
